config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :restaurants
  get '/search' , to: 'pages#index'
  root 'pages#top'
  get '/how_to', to: 'pages#how_to'

  post 'restaurants/:id/description', to: 'restaurant_descriptions#create'
  patch 'restaurants/:id/description', to: 'restaurant_descriptions#update'
  put   'restaurants/:id/description', to: 'restaurant_descriptions#update'

  post 'restaurant/image/food', to: 'restaurant_images#set_food_images'
  delete 'restaurant/image/food/:id', to: 'restaurant_images#destroy_food_images'

  post 'restaurant/image/drink', to: 'restaurant_images#set_drink_images'
  delete 'restaurant/image/drink/:id', to: 'restaurant_images#destroy_food_images'

  post 'restaurant/image/facility', to: 'restaurant_images#set_facility_images'
  delete 'restaurant/image/facility/:id', to: 'restaurant_images#destroy_facility_images'




  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
}

  devise_scope :user do
    get 'users/complete', to: 'users/registrations#complete'

    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
    get 'users/:id' => 'users/registrations#show', as: 'user_show'

  end

  devise_for :restaurants, controllers: {
      sessions: 'restaurants/sessions',
      passwords: 'restaurants/passwords',
      registrations: 'restaurants/registrations'
  }

  get 'restaurants/:id', to: 'pages#show', as: 'restaurant_show'

  resources :coupons , only: [:create, :destroy]
  resources :comments , only: [:create, :destroy]

  get '/coupon/use/:restaurant_id/:coupon_id', to: 'coupons#use_coupon'



  # devise_for :users, :controllers => {
  #     :registrations => 'users/registrations'
  # }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants
  has_many :sub_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  has_many :used_coupons
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_taggable_on :keywords
  has_one :restaurant_description, dependent: :destroy
  has_many :restaurant_drink_images, dependent: :destroy
  has_many :restaurant_food_images, dependent: :destroy
  has_many :restaurant_facility_images, dependent: :destroy

  has_many :coupons, dependent: :destroy
  has_many :comments, dependent: :destroy

  belongs_to :category
  belongs_to :sub_category

  geocoded_by :address
  after_validation :geocode

  mount_uploader :image, ImageUploader

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.search_by_name(search)
    if search
      Restaurant.where(['restaurant_name LIKE ?', "%#{search}%"])
    else
      Restaurant.all #全て表示。
    end
  end
end

app/models/restaurant_description.rb
class RestaurantDescription < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant_drink_image.rb
class RestaurantDrinkImage < ApplicationRecord
  belongs_to :restaurant
  mount_uploader :image, RestaurantDrinkImageUploader
end

app/models/restaurant_food_image.rb
class RestaurantFoodImage < ApplicationRecord
  belongs_to :restaurant
  mount_uploader :image, RestaurantFoodImageUploader
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
end

app/models/used_coupon.rb
class UsedCoupon < ApplicationRecord
  belongs_to :user
  belongs_to :coupon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default users modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :accepted_valid?

  has_many :used_coupons
  has_many :comments




  private

    def accepted_valid?
      errors.add(:accepted, 'して頂かない場合は、登録できません。') unless accepted == true
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if current_user

      comment = Restaurant.find(params[:restaurant_id]).comments.build(comment_params)
      comment.user_id = current_user.id
      comment.reputation = average_reputation_by_comment(comment)

      comment.save!

      redirect_to "/restaurants/#{params[:restaurant_id]}"

    else

      flash[:alert] = "レビュー投稿には会員登録が必要です。"

      redirect_to "/users/sign_up"

    end

  end

  def destroy
    Comment.find(params[:id]).destroy
  end

  private
    def comment_params
      params.require(:comment).permit(:comment, :restaurant_id, :food_reputation, :drink_reputation,
                                      :service_reputation, :coupon_reputation)
    end

    def average_reputation_by_comment(comment)
      all_reputation = comment.food_reputation+comment.drink_reputation+comment.coupon_reputation+comment.service_reputation

      (all_reputation/4).round(2)
    end


end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def create
    current_restaurant.coupons.create(coupon_params)

    redirect_to "/restaurants/edit"
  end

  def destroy
    Coupon.find(params[:id]).destroy
    redirect_to "/restaurants/edit"
  end

  def use_coupon
    if current_user
      UsedCoupon.create(user_id: current_user.id, coupon_id: params[:coupon_id])
      redirect_to restaurant_show_url(params[:restaurant_id])
    else
      flash[:alert] = "クーポンのご利用にはログインが必要です。"
      redirect_to "/users/sign_in"
    end
  end

  private
    def coupon_params
      params.require(:coupon).permit(:name, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
    @restaurants = Restaurant.page(params[:page]).per(5).order('created_at DESC')
    @tags = ActsAsTaggableOn::Tag.most_used(3)
    @tags = Restaurant.all_tags

    @prior_restaurants = Restaurant.where(priority: true)


  end

  def show
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.restaurant_description
      @restaurant_description = @restaurant.restaurant_description
    else
      @restaurant_description = RestaurantDescription.new

    end
    @drink_images = @restaurant.restaurant_drink_images.all
    @food_images = @restaurant.restaurant_food_images.all

    @coupons = @restaurant.coupons.all
    @comment = User.first.comments.build
    @comments = @restaurant.comments.all
  end

  def index
    if params[:category].present? && params[:name].present?

      restaurants = Restaurant.tagged_with(params[:category])

      @restaurants = restaurants.select{|k,v| k==:restaurant_name && v==params[:name]}

    elsif params[:category] && params[:name].blank?

      @restaurants = Restaurant.tagged_with(params[:category])

    elsif params[:category].blank? && params[:name]

      @restaurants = Restaurant.search_by_name(params[:name])

    end

    @searched_name = params[:name]
    @searched_category = params[:category]

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def average_reputation(restaurant)
    unless restaurant.comments.blank?
      restaurant.comments.average(:reputation)
    else
      return 100
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurant_images_helper.rb
module RestaurantImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datestyle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!--    ここから追加-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="shortcut icon" href="images/favicon1.png">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p|Source+Sans+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fugaz+One|Lobster|Monoton" rel="stylesheet">
    <title>DateStyle</title>
<!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
<!--    ここまで追加-->
  </head>
  <body>
    <div class="mobile">
      <%= render "shared/header" %>



      <%= yield %>
      <%= render "shared/footer" %>
    </div>
    <div class="desktop">
      <div>
        <h1>Coming Soon !!</h1>
        <p>現在準備中</p>
        <p>近日中に公開予定です。</p>
      </div>
    </div>

  </body>
</html>

app/views/pages/_drink_images_list.html.erb
<% images.each do |content| %>
  <a class="menuChild" id="drinkId_<%= content.id %>" href="#popProductId1">
    <img src=<%= content.image.to_s %> alt="" width="100%" height="120px" style="border-radius:30px 30px 0 0">
    <div class="menuText">
      <div class="menuName">
        <h4><%= content.name %></h4>
        <span class="menuPlace"><%= content.price %></span>
      </div>
      <p class="menuMore">詳しく見る</p>
    </div>
  </a>

  <div class="mfp-iframe-scaler mfp-hide pop_product" id="popDrinkId_<%= content.id %>">
    <div class="pop_product_img">
      <img src="" alt="" width="100%" height="100%">
    </div>
    <div class="pop_product_text">
      <p class="pop_product_name"><%= content.name %></p>
      <p class="pop_product_price"><%= content.price %></p>
      <p class="pop_product_descriction"><%= content.content %></p>
    </div>
  </div>
<% end %>


<script>
    <% images.each do |content| %>

    $(document).ready(function() {

        $('a#drinkId_<%= content.id %>').magnificPopup({
            items: {
                src: '#popDrinkId_<%= content.id %>'
            },
            type: 'inline'
        });

    });

    <% end %>

</script>

app/views/pages/_food_images_list.html.erb
<% images.each do |content| %>
  <a class="menuChild" id="foodId_<%= content.id %>" href="#popProductId1">
    <img src=<%= content.image.to_s %> alt="" width="100%" height="120px" style="border-radius:30px 30px 0 0">
    <div class="menuText">
      <div class="menuName">
        <h4><%= content.name %></h4>
        <span class="menuPlace"><%= content.price %></span>
      </div>
      <p class="menuMore">詳しく見る</p>
    </div>
  </a>

  <div class="mfp-iframe-scaler mfp-hide pop_product" id="popFoodId_<%= content.id %>">
    <div class="pop_product_img">
      <img src="" alt="" width="100%" height="100%">
    </div>
    <div class="pop_product_text">
      <p class="pop_product_name"><%= content.name %></p>
      <p class="pop_product_price"><%= content.price %></p>
      <p class="pop_product_descriction"><%= content.content %></p>
    </div>
  </div>
<% end %>



<script>
    <% images.each do |content| %>

    $(document).ready(function() {

        $('a#foodId_<%= content.id %>').magnificPopup({
            items: {
                src: '#popFoodId_<%= content.id %>'
            },
            type: 'inline'
        });

    });

    <% end %>

</script>

app/views/pages/how_to.html.erb
<%= image_tag 'how_to.jpg', width: "100%", height: "100%" %>

app/views/pages/index.html.erb
<section id="newArrival" class="section">
  <h2 class="secTitle">検索結果</h2>
  <h3>店舗名：<%= @searched_name %> カテゴリー名：<%= @searched_category %></h3>
  <div class="articleLoop">
    <% if !@restaurants.blank? %>
      <%= render "restaurant_list", restaurants: @restaurants %>
    <% else %>
      <br>

      条件に合うお店がありませんでした。
    <% end %>

  </div>
</section>

app/views/pages/show.js.erb
//$(document).on('turbolinks:load', function() {


// $('a.couponButton').magnificPopup({
//     items: {
//         src:'#popup_0yen'
//     },
//     type:'inline'
// });
//    $('.popUpLink').magnificPopup({
//        items: {
//            src: '#popup_store'
//        },
//        type: 'inline'
//    });
//    $('a#ProductId1').magnificPopup({
//        items: {
//            src: '#popProductId1'
//        },
//        type: 'inline'
//    });
//    $('a#couponId').magnificPopup({
//        items: {
//            src: '#popCouponId'
//        },
//        type: 'inline'
//    });

//});

app/views/pages/top.html.erb
<!--<div class="eyecatch">-->
<!--  <div class="eyecatchInner">-->
<!--    <div class="eyecatchImg"></div>-->
    <%#= form_tag search_path,method: :get, class: "eyecatchForm" do %>

<!--      <div class="keywordSearch">-->
        <%#= text_field_tag :name,"", class: "", placeholder: "店舗名で検索" %>
<!--      </div>-->
<!--      <div class="categorySearch">-->
        <%#= text_field_tag :category,"", class: "" , placeholder: "タグで検索" %>
<!--      </div>-->

<!--      <div class="eyecatchButton">-->
        <%#= button_tag "検索", class: "eyecatchButton" %>
<!--      </div>-->
    <%# end %>
<!--  </div>-->
<!--</div>-->
<!--  <section id="registration" class="section">-->
<!--    <a class="registaBtn" href="/users/sign_up"><p>今すぐ登録で飲み放題０円</p><i></i></a>-->
<!--    <a class="registaBtn" href="/restaurants/sign_in"><p>加盟店のお問い合わせはこちら</p><i></i></a>-->
<!--  </section>-->
<!--  category loop-->
<!--<section id="category" class="category section">-->
<!--  <h2 class="secTitle">カテゴリーからお店を探す</h2>-->
<!--  <ul class="categoryList">-->

  <%# @tags.each do |tag| %>
<!--    <li><%#= link_to tag.name, search_path(category: tag.name) %></li>-->
    <%# end %>
<!--  </ul>-->

<!--</section>-->
<!-- article loop>

</article> -->
<%# unless @prior_restaurants.blank? %>
<!--  <section id="newArrival" class="section">-->
<!--    <h2 class="secTitle">おすすめ</h2>-->
<!--    <div class="articleLoop">-->

        <%#= render 'restaurant_list', restaurants: @prior_restaurants %>


<!--    </div>-->
<!--  </section>-->
<%# end %>

<!--<section id="newArrival" class="section">-->
<!--  <h2 class="secTitle">新着</h2>-->
<!--  <div class="articleLoop">-->

<!--    <div id="load_page">-->
      <%#= render 'restaurant_list', restaurants: @restaurants %>
<!--    </div>-->
    <%#= link_to_next_page @restaurants, 'もっと見る', remote: true, id: 'more_link' %>

<!--  </div>-->
<!--</section>-->










<div class="eyecatch">
  <div class="eyecatchInner">
    <div class="eyecatchImg"></div>
    <%= form_tag search_path,method: :get, class: "eyecatchForm" do %>

      <div class="keywordSearch">
        <%= text_field_tag :name,"", class: "", placeholder: "店舗名で検索" %>
      </div>
      <div class="categorySearch">
        <%= text_field_tag :category,"", class: "" , placeholder: "タグで検索" %>
      </div>

        <%= button_tag "検索", class: "eyecatchButton" %>
    <% end %>
  </div>
</div>
<section id="registration" class="section">
  <a class="registaBtn" href="/users/sign_up"><p>今すぐ登録で飲み放題０円<i class="fas fa-plus fa-fw"></i></p><i></i></a>
  <a class="registaBtn" href="/restaurants/sign_in"><p>加盟店のお問い合わせはこちら<i class="fas fa-envelope fa-fw"></i></p><i></i></a>
</section>
<!--  category loop-->
<section id="category" class="category section">
  <h2 class="secTitle">カテゴリーからお店を探す</h2>
  <ul class="categoryList">

    <% @tags.each do |tag| %>
      <li><%= link_to tag.name, search_path(category: tag.name) %></li>
    <% end %>
  </ul>

</section>
<!-- article loop>

</article> -->
<% unless @prior_restaurants.blank? %>
  <section id="newArrival" class="section">
    <h2 class="secTitle">おすすめ</h2>
    <div class="articleLoop">

<!--      <div id="load_page">-->
      <div class="restaurant_container">
        <div class="restaurant_wrap">

            <%= render 'restaurant_list', restaurants: @prior_restaurants %>
        </div>
      </div>
      <!--      </div>-->

    </div>
  </section>
<% end %>

<section id="newArrival" class="section">
  <h2 class="secTitle">新着</h2>
  <div class="articleLoop">

<!--    <div id="load_page">-->
    <div class="restaurant_container">
      <div class="restaurant_wrap" id="load_page">
      <%= render 'restaurant_list', restaurants: @restaurants %>
      </div>

<!--    </div>-->
    <div class='more_link'><%= link_to_next_page @restaurants, 'もっと見る >>', remote: true, id: 'more_link' %></div>
    </div>

  </div>
</section>

app/views/pages/top.js.erb
$('#load_page').append("<%= escape_javascript(render 'restaurant_list',{restaurants:@restaurants}) %>")
$('#more_link').replaceWith("<%= escape_javascript(link_to_next_page(@restaurants, 'もっと見る', remote: true, id: 'more_link')) %>");

app/views/shared/_footer.html.erb
<footer>
  <ul class="site_map">
    <li><a href="#">ヘルプ</a></li>
    <li><a href="#">サービス利用規約</a></li>
    <li><a href="#">個人情報保護方針</a></li>
    <li><a href="#">特定商法に基づく表示</a></li>
    <li><a href="#">著作権情報</a></li>
    <li><a href="#">お問い合わせ</a></li>
    <li><a href="#">ユーザー情報</a></li>
    <li><a href="#">datestyleの使い方</a></li>
  </ul>

  <div class="top_footer">
    <small>copyright©DateStyle.inc All Rights Reserved</small>
  </div>

</footer>

app/views/shared/_header.html.erb
<%# if current_user %>
<!--  ログイン時-->
<!--  <header class="header">-->
    <%#= link_to "", root_url, class: "headerLogo" %>
<!--    <nav class="headerNav">-->
      <%#= link_to current_user.name, user_show_path(current_user.id) %>
<!--      <div class="menuButton">-->
<!--        <div id="navToggle">-->
<!--          <span></span><span></span><span></span>-->
<!--        </div>-->
<!--      </div>-->
<!--    </nav>-->
<!--  </header>-->
<!--  <aside>-->
<!--    <div class="side">-->
<!--      <a href="/"><div class="sideImg"></div></a>-->
<!--      <ul class="sideNav">-->
<!--        <a href="/how_to"><li>datestyleの使い方</li></a>-->
<!--        <a href="#"><li>お知らせ</li></a>-->
<!--        <a href="/users/<%#= current_user.id %>"><li>ユーザー情報</li></a>-->
<!--        <a href="#"><li>ヘルプ</li></a>-->
<!--  <!--      <a href="#"><li>サービス利用規約</li></a>-->
<!--  <!--      <a href="#"><li>個人情報保護方針</li></a>-->
<!--  <!--      <a href="#"><li>特定商法に基づく表示</li></a>-->
<!--  <!--      <a href="#"><li>著作権情報</li></a>-->
<!--  <!--      <a href="#"><li>ご意見・ご要望</li></a>-->
<!--  <!--      <a href="#"><li>ユーザー情報</li></a>-->
<!--  <!--      <a href="#"><li>著作権情報</li></a>-->
        <%#= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<!--      </ul>-->
<!--    </div>-->
<!--  </aside><%# else %>-->
<!--  未ログイン時-->

<!--  <header class="header">-->
    <%#= link_to "", root_url, class: "headerLogo" %>
<!--    <nav class="headerNav">-->
<!--      <a class="headerBtn" href="/users/sign_up"><p>新規登録</p></a>-->
<!--      <a class="headerBtn" href="/users/sign_in"><p>ログイン</p></a>-->
<!--      <div class="menuButton">-->
<!--        <div id="navToggle">-->
<!--          <span></span><span></span><span></span>-->
<!--        </div>-->
<!--      </div>-->
<!--    </nav>-->
<!--  </header>-->
<!--  <aside>-->
<!--    <div class="side">-->
<!--      <a href="/"><div class="sideImg"></div></a>-->
<!--      <ul class="sideNav">-->
<!--        <a href="/how_to"><li>datestyleの使い方</li></a>-->
<!--        <a href="/users/sign_up"><li>新規登録</li></a>-->
<!--        <a href="/users/sign_in"><li>ログイン</li></a>-->
<!--        <!--        <a href="#"><li>会員登録情報</li></a>-->
<!--        <!--      <a href="#"><li>サービス利用規約</li></a>-->
<!--        <!--      <a href="#"><li>個人情報保護方針</li></a>-->
<!--        <!--      <a href="#"><li>特定商法に基づく表示</li></a>-->
<!--        <!--      <a href="#"><li>著作権情報</li></a>-->
<!--        <!--      <a href="#"><li>ご意見・ご要望</li></a>-->
<!--        <!--      <a href="#"><li>ユーザー情報</li></a>-->
<!--        <!--      <a href="#"><li>著作権情報</li></a>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </aside>-->

<%# end %>











<% if current_user %>
  <!--  ログイン時-->
  <header class="header">
    <%= link_to "", root_url, class: "headerLogo" %>
    <nav class="headerNav">
      <%= link_to current_user.name, user_show_path(current_user.id) %>
      <div class="menuButton">
        <div id="navToggle">
          <span></span><span></span><span></span>
        </div>
      </div>
    </nav>
  </header>
  <aside>
    <div class="side">
      <a href="/"><div class="sideImg"></div></a>
      <ul class="sideNav">
        <a href="/how_to"><li><i class="fas fa-align-left fa-fw"></i>datestyleの使い方</li></a>
        <a href="#"><li><i class="fas fa-question-circle"></i>ヘルプ</li></a>
        <a href="#"><li><i class="fas fa-bookmark"></i>サービス利用規約</li></a>
        <a href="#"><li><i class="fas fa-envelope"></i>お問い合わせ</li></a>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <li>ログアウト</li>
        <% end %>
      </ul>
    </div>
  </aside><% else %>
  <!--  未ログイン時-->

  <header class="header">
    <%= link_to "", root_url, class: "headerLogo" %>
    <nav class="headerNav">
      <a class="headerBtn" href="/users/sign_up"><p>新規登録</p></a>
      <a class="headerBtn" href="/users/sign_in"><p>ログイン</p></a>
      <div class="menuButton">
        <div id="navToggle">
          <span></span><span></span><span></span>
        </div>
      </div>
    </nav>
  </header>
  <aside>
    <div class="side">
      <!-- <a href="/"><div class="sideImg"></div></a> -->
      <ul class="sideNav">
        <a href="/how_to"><li><p><i class="fas fa-align-left fa-fw"></i>datestyleの使い方</p></li></a>
        <a href="/users/sign_up"><li><i class="fas fa-plus fa-fw"></i>新規登録</li></a>
        <a href="/users/sign_in"><li><i class="fas fa-sign-in-alt fa-fw"></i>ログイン</li></a>
        <a href="#"><li><i class="fas fa-question-circle"></i>ヘルプ</li></a>
        <a href="#"><li><i class="fas fa-bookmark"></i>サービス利用規約</li></a>
        <a href="#"><li><i class="fas fa-envelope"></i>お問い合わせ</li></a>


      </ul>
    </div>
  </aside>

<% end %>